knpu_oauth2_client:
  clients:
    yconnect_client:
      type: generic
      provider_class: Customize\Security\OAuth2\Client\Provider\Yahoo\YConnect
      client_id: ''
      client_secret: ''
      redirect_route: yahoo_callback

      